db:
    resource: "@DBBundle/Resources/config/routing.yml"
    prefix:   /

doc:
    resource: "@DocBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

