base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

db:
    resource: "@DBBundle/Resources/config/routing.yml"
    prefix:   /

doc:
    resource: "@DocBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

