category_homepage:
    pattern: /category
    defaults: { _controller: ApiBundle:Category:index }

category_get_all:
    pattern: /api/categories
    defaults: { _controller: ApiBundle:Category:list }
category_create:
    pattern: /api/category/create
    defaults: { _controller: ApiBundle:Category:create }
    requirements:
        _method: post
