<?php

namespace Site\DBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrederedItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedItemRepository extends EntityRepository
{
}
